services:
  psql:
    container_name: postgres
    image: postgres:16.2-alpine3.18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    networks:
      - backend_network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - psql
    networks:
      - backend_network
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  db: